### ISSUE TITLE
libdarknet.so Error

### ISSUE THREAD

**Issue by shootingliu** [qiaoguan/Fall-detection#2]
Hello @qiaoguan 

I got the <OSError: libdarknet.so: cannot open shared object file: No such file or directory> when I use gq.py.

I also found that you have asked the same question in darknet, so how did you deal with it finally?

Thanks in advance.

**Comment by shootingliu** [comment]
I got it.

**Comment by qiaoguan** [comment]
i run the source code on two computers, one worked, while the other one failed, how did you solve this problem?

**Comment by Jialeen** [comment]
@shootingliu How did you solved the problem, and I met the problem also. @qiaoguan Did you solve the problem?

**Comment by shootingliu** [comment]
Hi @qiaoguan @Jialeen 
Sorry for late reply.
I just added the absolute path for libdarknet.so in python/darknet.py.
