### ISSUE TITLE
OsError: wrong ELF Class : ELFCLASS64

### ISSUE THREAD

**Issue by KimChwee** [qiaoguan/Fall-detection#5]
Hi ! The work here is great and I am trying to test this project of yours.
Overcome many setup issues and but stucked at the above error.

Tried google/youtube and read thru the Darknet site but am not able to find any solutions. Can you help?

**Comment by qiaoguan** [comment]
hi,  can you provide some more details about the error,   where it happens?  you can provide some screenshot

**Comment by KimChwee** [comment]
Thank you for your time!
1) Downloaded the codes and installed OpenCV2 etc no issues
2) Tried to run the program and encountered error with libdarknet.so file not found. I have corrected the path and this part is fixed.
3) Re-run gq.py and got another OSError:
![image](https://user-images.githubusercontent.com/34203731/40164714-de2e2ebc-59ec-11e8-88dd-b4462e2ff41c.png)

**Comment by qiaoguan** [comment]
when you alter the makefile, remake it,  i haven't encountered this problem,  i  searched this error on the internet,  The reason may be that linux and dynamic link library are not compatible(64 bit, 32bit),  you can search the internet,  hope it can help you!

**Comment by KimChwee** [comment]
Thanks for the reply! I saw the solution as re-make as mentioned but exactly what is re-make in this case?
eg. which folder to go and what is the command to re-make libdarknet.so

**Comment by qiaoguan** [comment]
i just mean when you alter the makefile,  recompile the makefile.  you can google  " wrong ELF class: ELFCLASS64"  to find the reason!

**Comment by KimChwee** [comment]
Found the fixed.
1) edit Makefile with sudo nano Makefile
2) Change any of the first 3 option from 0 to 1 or vice versa (as long as you make some changes). Save and exit
3) run "make" at command line (since changes detected, a new libdarknet.so file will be re-compiled according to your OS bit (32 / 64)
4) edit Makefile and revert to whatever setting you want
5) run make again
